# Generated by Django 4.2.6 on 2023-11-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Studnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="포스트 제목")),
                ("content", models.TextField(verbose_name="포스트내용")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to="post", verbose_name="썸네일 이미지"
                    ),
                ),
            ],
        ),
    ]
